server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51So1yVAZtdRpxJsnkXg7ddVlYwU63vKuv2gekt7hezFL7PE68QsENyrMr2tjjIMUe1ANqkO7M7UMEuqAgq0kxLdV00SYVwNFRx
  webhook:
    secret: whsec_55fceb6140aa36aaa94f14fd170eb57cfb9a0d4fabacabf17dcb7791b7994a72
